### PR TITLE
Fix dependencies for hfb and laser_odom

### PR DESCRIPTION
**Pull request by ke-sun**
Not sure if I missed anything, these two repos don't compile without the fix.

### CODE REVIEW

**Comment by tdinesh** [comment]
are you on 18.04? I do not have issue on 16.04

@danmox are we ready to merge everything in master?

**Comment by ke-sun** [comment]
No. I am on 16.04 with ROS Kinetic

**Comment by kartikmohta** [comment]
@tdinesh This is due to the strict linker flags set by most people working on FLA. You can set the env variable `export LDFLAGS="-Wl,--as-needed,--no-undefined"` and then clean/recompile to see the error.

**Comment by danmox** [comment]
@tdinesh I have yet to follow up with @kelsey-saulnier regarding a desired launch file structure, so I would hold off on merging everything

**Comment by tdinesh** [comment]
@danmox Can we aim for sometime early this month? 
@kartikmohta yes, I can reproduce the error with the flags. Is there a way to set it just for a workspace with catkin tools?

**Comment by kartikmohta** [comment]
@tdinesh I don't think you can set an env variable through catkin tools, I just set it for everything through the bashrc. The main effect is that it catches errors in the CMakeLists file, so might lead to errors when using people's packages which you need to fix (which I think is a positive side-effect but you might not think of it as such :stuck_out_tongue:)

**Comment by tdinesh** [comment]
The main issue is I have to deal with Dr.Loianno's packages :stuck_out_tongue:)

**Comment by kartikmohta** [comment]
> The main issue is I have to deal with Dr.Loianno's packages :stuck_out_tongue:

You have my condolences :expressionless:

**Comment by danmox** [comment]
@tdinesh I think that's reasonable

**Pull request merged**
